algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2023
// Seção de Declarações 
var
NUM:inteiro

inicio
ESCREVAL("DIGITE UM NUMERO INTEIRO")
LEIA(NUM)

SE (NUM > 0) ENTAO
     ESCREVAL("O NUMERO",NUM," É POSITIVO)
SENAO
     SE (NUM < 0) EN
          ESCREVAL("O NUMERO",NUM," É NEGATIVO)
     SENAO
          ESCREVAL("O NUMERO",NUM, " É NEUTRO)
     FIMSE
FIMSE
fimalgoritmo
